# Generated by Django 2.2 on 2023-08-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationpost',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='educationpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='educationpost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='educationpost',
            name='total_views',
        ),
        migrations.RemoveField(
            model_name='educationpost',
            name='updated',
        ),
        migrations.AlterField(
            model_name='educationpost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='education/%Y%m%d/'),
        ),
    ]
