# Generated by Django 2.2 on 2023-08-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20230807_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='VideoList',
        ),
    ]
