# Generated by Django 2.2 on 2023-08-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Job',
            new_name='Jobname',
        ),
    ]
