# Generated by Django 2.2 on 2023-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0003_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='Jobname',
            new_name='Management_Job',
        ),
        migrations.AlterField(
            model_name='management',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='Management_Job/%Y%m%d/'),
        ),
    ]
