# Generated by Django 2.2 on 2023-08-12 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_auto_20230812_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sales_Job', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(blank=True, upload_to='Sales_Job/%Y%m%d/')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
