# Generated by Django 2.2 on 2023-08-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0006_others'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Others',
            new_name='Other',
        ),
        migrations.RenameField(
            model_name='other',
            old_name='Others_Job',
            new_name='Other_Job',
        ),
    ]
